# Numpy

In [5]:
import numpy as np

#  Creating Arrays

In [6]:
mylist =[1,2,3]
x = np.array(mylist)
x

array([1, 2, 3])

In [7]:
y =  np.array([4,5,6])
y

array([4, 5, 6])

In [9]:
m = np.array([[7,8,9], [10,11,12]])
m

array([[ 7,  8,  9],
       [10, 11, 12]])

In [10]:
m.shape

(2, 3)

In [15]:
n =  np.arange(0,30,2)
n

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [17]:
n = n.reshape(3,5)
n

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28]])

In [18]:
o = np.linspace(0, 4, 9)
o

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. ])

In [21]:
o.resize(3,3)
o

array([[0. , 0.5, 1. ],
       [1.5, 2. , 2.5],
       [3. , 3.5, 4. ]])

In [23]:
np.ones([3,2])

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [24]:
np.zeros([3,2])

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [25]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [28]:
np.diag([4,5,6])

array([[4, 0, 0],
       [0, 5, 0],
       [0, 0, 6]])

In [29]:
np.array([1,2,3] * 3)

array([1, 2, 3, 1, 2, 3, 1, 2, 3])

In [30]:
np.repeat([1,2,3],3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

In [32]:
p = np.ones([2,3], int)
p

array([[1, 1, 1],
       [1, 1, 1]])

In [34]:
np.vstack([p, 2*p])

array([[1, 1, 1],
       [1, 1, 1],
       [2, 2, 2],
       [2, 2, 2]])

In [35]:
np.hstack([p, 2*p])

array([[1, 1, 1, 2, 2, 2],
       [1, 1, 1, 2, 2, 2]])

# Operations

In [38]:
print('x', x)
print('y', y)
'x + y', x + y

x [1 2 3]
y [4 5 6]


('x + y', array([5, 7, 9]))

In [39]:
x * y

array([ 4, 10, 18])

In [40]:
x**2

array([1, 4, 9])

In [42]:
x.dot(y)

32

In [44]:
z = np.array([y, y**2])
z

array([[ 4,  5,  6],
       [16, 25, 36]])

In [45]:
z.shape

(2, 3)

In [46]:
z.T #tranpose

array([[ 4, 16],
       [ 5, 25],
       [ 6, 36]])

In [47]:
z.T.shape

(3, 2)

In [48]:
z.dtype

dtype('int64')

In [49]:
z =  z.astype('f')
z.dtype

dtype('float32')

In [50]:
z

array([[ 4.,  5.,  6.],
       [16., 25., 36.]], dtype=float32)

In [51]:
a = np.array([-4,-2,1,3,5])

In [52]:
a.sum()

3

In [53]:
a.min()

-4

In [54]:
a.max()

5

In [55]:
a.mean()

0.6

In [56]:
a.std()

3.2619012860600183

In [58]:
a.argmax()

4

In [59]:
a.argmin()

0

# Indexing / Slice

In [62]:
s = np.arange(36)
s

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35])

In [63]:
s[0], s[4], s[0:3]

(0, 4, array([0, 1, 2]))

In [64]:
s[1:5]

array([1, 2, 3, 4])

In [65]:
s[-4:]

array([32, 33, 34, 35])

In [66]:
s[-5::-2]

array([31, 29, 27, 25, 23, 21, 19, 17, 15, 13, 11,  9,  7,  5,  3,  1])

In [97]:
s[1::2]

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35])

In [98]:
r = np.arange(36)
r.resize((6,6))
r

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [99]:
r[2, 2]

14

In [100]:
r[3, 3:6]

array([21, 22, 23])

In [101]:
r[:2, :-1]

array([[ 0,  1,  2,  3,  4],
       [ 6,  7,  8,  9, 10]])

In [102]:
r[:-1, ::2]

array([[ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16],
       [18, 20, 22],
       [24, 26, 28]])

In [113]:
r.reshape(36)[::7] #get diag

array([ 0,  7, 14, 21, 28, 35])

In [117]:
r[2:4,2:4]

array([[14, 15],
       [20, 21]])

In [85]:
r[r > 30]

array([31, 32, 33, 34, 35])

In [86]:
r[r > 30] = 30
r

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 30, 30, 30, 30, 30]])

In [87]:
old = np.array([[1, 1, 1],
                [1, 1, 1]])

new = old.copy()
new[:, 0] = 0

print(old)


[[1 1 1]
 [1 1 1]]


# Interating Over Arrays

In [88]:
test =  np.random.randint(0, 10,(4,3))
test

array([[5, 9, 7],
       [5, 1, 1],
       [7, 1, 8],
       [3, 5, 3]])

In [89]:
for row in test:
    print(row)

[5 9 7]
[5 1 1]
[7 1 8]
[3 5 3]


In [90]:
for i in range(len(test)):
    print(test[i])

[5 9 7]
[5 1 1]
[7 1 8]
[3 5 3]


In [91]:
for i, row in enumerate(test):
    print('row', i, 'is', row)

row 0 is [5 9 7]
row 1 is [5 1 1]
row 2 is [7 1 8]
row 3 is [3 5 3]


In [93]:
test2 = test**2
test2

array([[25, 81, 49],
       [25,  1,  1],
       [49,  1, 64],
       [ 9, 25,  9]])

In [94]:
for i, j in zip(test, test2):
    print(i, '+', j, '=', i + j)

[5 9 7] + [25 81 49] = [30 90 56]
[5 1 1] + [25  1  1] = [30  2  2]
[7 1 8] + [49  1 64] = [56  2 72]
[3 5 3] + [ 9 25  9] = [12 30 12]


In [95]:
['a', 'b', 'c'] + [1, 2, 3]

['a', 'b', 'c', 1, 2, 3]

In [96]:
type(lambda x: x+1)

function